version: "3.9"
services:

  devicehub:
    init: true
    image: dkr-dsg.ac.upc.edu/ereuse/devicehub:dpp__bcb4c696
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=postgres
      - DB_DATABASE=${DB_DATABASE}
      - HOST=${HOST}
      - EMAIL_DEMO=${EMAIL_DEMO}
      - PASSWORD_DEMO=${PASSWORD_DEMO}
      - JWT_PASS=${JWT_PASS}
      - SECRET_KEY=${SECRET_KEY}
      - DEVICEHUB_HOST=${DEVICEHUB_HOST}
      - URL_MANUALS=${URL_MANUALS}
      - AUTHORIZED_CLIENT_URL=${CLIENT_ID_DEVICEHUB_HOST}
      - DPP_MODULE=n
      - IMPORT_SNAPSHOTS=${IMPORT_SNAPSHOTS}
    ports:
      - 5000:5000
    volumes:
      - ${SNAPSHOTS_PATH:-./examples/snapshots}:/mnt/snapshots:ro
      - shared:/shared:rw

  postgres:
    image: dkr-dsg.ac.upc.edu/ereuse/postgres:dpp__bcb4c696
    # 4. To create the database.
    # 5. Give permissions to the corresponding users in the database.
    #   extra src https://github.com/docker-library/docs/blob/master/postgres/README.md#environment-variables
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_DATABASE}
    # DEBUG
    #ports:
    #  - 5432:5432
    # TODO persistence
    #volumes:
    #  - pg_data:/var/lib/postgresql/data

    # TODO https://testdriven.io/blog/dockerizing-django-with-postgres-gunicorn-and-nginx/
    #nginx

volumes:
  shared:
