CREATE DATABASE {db};
CREATE USER {user} WITH PASSWORD '{pass}';
GRANT ALL PRIVILEGES ON DATABASE {db} TO {user};
\c {db}
CREATE EXTENSION pgcrypto SCHEMA public;
CREATE EXTENSION ltree SCHEMA public;
CREATE EXTENSION citext SCHEMA public;
CREATE EXTENSION pg_trgm SCHEMA public;
